[package]
name = "skeleton-that-runs-across-your-screen-sometimes"
version = "0.1.0"
edition = "2021"
repository = "github.com/olimci/skeleton-that-runs-across-your-screen-sometimes"

[dependencies]
glfw = { version = "0.62", default-features = false, features = ["all", "src-build"] }
glow = "0.17"
image = "0.25"
fastrand = "2"
include_dir = "0.7.4"
rodio = { version = "0.22.2", default-features = false, features = ["playback", "mp3"] }
